additionalRepositories:
  - url: https://github.com/cloud-native-toolkit/ascent-bff
    checkoutLocation: ascent-bff

workspaceLocation: ascent-ui/main.code-workspace

tasks:
  - name: iascable
    before: |
      cd ../iascable
    init: |
      npm ci
    command: |
      npm run tdd

  - name: ascent-bff
    before: |
      cd ../ascent-bff
    init: |
      yarn cache clean
      yarn install
    command: |
      sudo apt install redis-server -y
      sudo service redis-server start
      yarn start:dev

  - name: ascent-ui
    init: |
      yarn cache clean
      yarn install
      yarn run build
    command: yarn start:dev
