import type { Metadata } from "next";
import {IBM_Plex_Mono, IBM_Plex_Sans} from "next/font/google";
import {Provider} from "jotai";

import "@/app/globals.scss";
import {Providers} from "@/app/providers";

const plexSans = IBM_Plex_Sans({
    weight: '400',
    subsets: ['latin'],
});

const plexMono = IBM_Plex_Mono({
    weight: '400',
    subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plexSans.className} ${plexMono.className}`}>
      <Provider>
        <Providers>{children}</Providers>
      </Provider>
      </body>
    </html>
  );
}
